packages:
  - apache2
  - php7.3
  - libapache2-mod-php7.3
  - php7.3-common
  - php7.3-mbstring 
  - php7.3-xmlrpc
  - php7.3-soap
  - php7.3-xml 
  - php7.3-intl
  - php7.3-mysql
  - php7.3-cli
  - php7.3-ldap
  - php7.3-zip
  - php7.3-curl

URLWP: 'https://wordpress.org/latest.tar.gz'

downloadFile: '/tmp/latest.tar.gz'

extractdir: '/tmp'

downloadFile2: '/tmp/archive.tar.gz'
